# 動的設定
http:
  routers:
    # 将来的に追加するバックエンドサービス用のルーター
    backend:
      rule: "Host(`api.localhost`)"
      service: backend-service
      entryPoints:
        - web

    # 将来的に追加する顧客向けフロントエンドサービス用のルーター
    frontend-customer:
      rule: "Host(`shop.localhost`)"
      service: frontend-customer-service
      entryPoints:
        - web

    # 将来的に追加する管理者向けフロントエンドサービス用のルーター
    frontend-admin:
      rule: "Host(`admin.localhost`)"
      service: frontend-admin-service
      entryPoints:
        - web

  # サービス定義（将来追加するサービスのためのプレースホルダー）
  services:
    backend-service:
      loadBalancer:
        servers:
          - url: "http://backend:8000"

    frontend-customer-service:
      loadBalancer:
        servers:
          - url: "http://frontend-customer:3000"

    frontend-admin-service:
      loadBalancer:
        servers:
          - url: "http://frontend-admin:3000"
