log_level: debug

server:
  port: 8080

database:
  host: mysql
  port: 3306
  user: ecommerce
  password: password
  name: ecommerce

aws:
  region: us-east-1
  endpoint: http://localstack:4566
  access_key: test
  secret_key: test
