version: "3"

vars:
  PROJECT_NAME: ecommerce-app

tasks:
  default:
    desc: プロジェクトのヘルプを表示
    cmds:
      - task -l
    silent: true

  setup:
    desc: プロジェクトのセットアップ
    cmds:
      - task: setup:backend
      - task: setup:frontend-customer
      - task: setup:frontend-admin

  setup:backend:
    desc: バックエンドのセットアップ
    dir: backend
    cmds:
      - go mod tidy
      - go mod verify

  setup:frontend-customer:
    desc: 顧客向けフロントエンドのセットアップ
    dir: frontend-customer
    cmds:
      - npm install

  setup:frontend-admin:
    desc: 管理者向けフロントエンドのセットアップ
    dir: frontend-admin
    cmds:
      - npm install

  up:
    desc: 開発環境を起動
    cmds:
      - docker compose up -d

  down:
    desc: 開発環境を停止
    cmds:
      - docker compose down

  logs:
    desc: コンテナのログを表示
    cmds:
      - docker compose logs -f {{.CLI_ARGS | default ""}}

  lint:
    desc: コードの静的解析を実行
    cmds:
      - task: lint:backend
      - task: lint:frontend-customer
      - task: lint:frontend-admin

  lint:backend:
    desc: バックエンドのlintを実行
    dir: backend
    cmds:
      - golangci-lint run ./...

  lint:frontend-customer:
    desc: 顧客向けフロントエンドのlintを実行
    dir: frontend-customer
    cmds:
      - npm run lint

  lint:frontend-admin:
    desc: 管理者向けフロントエンドのlintを実行
    dir: frontend-admin
    cmds:
      - npm run lint

  test:
    desc: テストを実行
    cmds:
      - task: test:backend
      - task: test:frontend-customer
      - task: test:frontend-admin

  test:backend:
    desc: バックエンドのテストを実行
    dir: backend
    cmds:
      - go test ./... -v

  test:frontend-customer:
    desc: 顧客向けフロントエンドのテストを実行
    dir: frontend-customer
    cmds:
      - npm test

  test:frontend-admin:
    desc: 管理者向けフロントエンドのテストを実行
    dir: frontend-admin
    cmds:
      - npm test

  localstack:create-bucket:
    desc: S3バケットを作成
    cmds:
      - awslocal s3 mb s3://product-images

  localstack:list-buckets:
    desc: S3バケットを一覧表示
    cmds:
      - awslocal s3 ls
