run:
  # タイムアウト時間（デフォルト: 1m）
  timeout: 5m

# 有効にするリンターの設定
linters:
  disable-all: true
  enable:
    - errcheck # エラーハンドリングの検証
    - gosimple # コードシンプル化の提案
    - govet # Goの怪しい構造を検出
    - ineffassign # 使用されない代入の検出
    - staticcheck # Go用の静的解析ツール
    - unused # 未使用コードの検出
    - gofmt # 標準フォーマッタによるフォーマット
    - goimports # インポート文の整理
    - misspell # よくあるスペルミスの検出
    - unconvert # 不要な型変換の削除
    - gosec # セキュリティの問題を検出
    - bodyclose # レスポンスボディを適切に閉じているか確認

# 特定のリンターの設定
linters-settings:
  errcheck:
    # io/ioutil.WriteFile, os.Create などの特定のエラーを無視する
    check-type-assertions: true
    check-blank: true

  govet:
    # 最新バージョンではcheck-shadowingはサポートされていないため削除
    enable:
      - shadow # シャドウ変数を検出する

  goimports:
    # インポートグループの順序を指定
    local-prefixes: github.com/y-nosuke/aws-observability-ecommerce

  gosec:
    # セキュリティの問題を検出する重大度
    severity: medium
    confidence: medium

# 発見した問題を除外する設定
issues:
  # 最大表示問題数（デフォルト: 50）
  max-issues-per-linter: 0
  max-same-issues: 0

  # 特定のパターンで問題を除外
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck # テストファイルではerrcheckを無効化

    - text: "G404: Use of weak random number generator"
      linters:
        - gosec # テスト用途などでの弱い乱数生成は許容

  # 解析から除外するディレクトリやファイル
  exclude-files:
    - ".*_test.go$"
  exclude-dirs-use-default: true
