FROM golang:1.24-alpine

# 開発ツールのインストール
RUN apk add --no-cache git curl

# Airのインストール (ホットリロード用)
RUN go install github.com/air-verse/air@latest

# migrate
RUN go install -tags mysql github.com/golang-migrate/migrate/v4/cmd/migrate@latest

# sqlboiler
RUN go install github.com/volatiletech/sqlboiler/v4@latest
RUN go install github.com/volatiletech/sqlboiler/v4/drivers/sqlboiler-mysql@latest

# oapi-codegen
RUN go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest

# goimports
RUN go install golang.org/x/tools/cmd/goimports@latest


# 作業ディレクトリの設定
WORKDIR /app

# ホストマシンのGoモジュールをキャッシュするためのマウントポイント
VOLUME ["/go/pkg/mod"]

# アプリケーションのポートを公開
EXPOSE 8080

# Airを使って開発サーバーを起動（ホットリロード）
CMD ["air", "-c", ".air.toml"]
