output = "internal/db/models"
no-tests = true
wipe = true
add-global-variants = true
add-panic-variants = true
no-context = false
no-hooks = false
no-auto-timestamps = false
tag-ignore = ["created_at", "updated_at", "deleted_at"]

[mysql]
  dbname = "ecommerce"
  host = "localhost"
  port = 3306
  user = "ecommerce_user"
  pass = "ecommerce_password"
  sslmode = "false"
  blacklist = ["schema_migrations"]

[[types]]
  [types.match]
    type = "types.Decimal"
  [types.replace]
    type = "decimal.Decimal"
  [types.imports]
    third_party = ['"github.com/shopspring/decimal"']
