pkgname = "models"
output = "internal/domain/models"
no-tests = false
add-global-variants = true
wipe = true
add-enum-types = true

[mysql]
  dbname = "ecommerce"
  host = "mysql"
  port = 3306
  user = "ecommerce"
  pass = "password"
  sslmode = "false"
