app:
  name: "aws-observability-ecommerce"
  version: "1.0.0"
  environment: "development"

server:
  port: 8000
  host: "0.0.0.0"
  read_timeout: 30
  write_timeout: 30

database:
  host: "localhost"
  port: 3306
  user: "root"
  password: "password"
  name: "ecommerce"
  max_open_conns: 25
  max_idle_conns: 25
  conn_max_lifetime: 5 # minutes

aws:
  use_localstack: true
  region: "ap-northeast-1"
  endpoint: "http://localstack:4566"
  access_key: "test"
  secret_key: "test"
  token: ""
  s3:
    bucket_name: "product-images"
    presigned_url_ttl: 3600 # seconds (1 hour)
    use_path_style: true

observability:
  logging:
    level: "info" # debug, info, warn, error
    format: "json" # json, text (開発時はtext推奨)
    enable_otel: true # OpenTelemetry連携有効化
    max_log_size_mb: 100 # 単一ログファイル最大サイズ

  otel:
    service_name: "aws-observability-ecommerce"
    service_version: "1.0.0"
    service_namespace: "ecommerce"
    deployment_environment: "development" # development, staging, production

    logging:
      enabled: true
      endpoint: "otel-collector:4317" # OTLP gRPC endpoint
      timeout: "10s"
      compression: "gzip"
      retry_enabled: true
      retry_initial_interval: "1s"
      retry_max_interval: "30s"
      retry_max_elapsed_time: "60s"
      export_timeout: "30s"
      max_queue_size: 2048
      max_export_batch_size: 512

    metrics:
      enabled: true
      endpoint: "otel-collector:4317" # OTLP gRPC endpoint
      timeout: "10s"
      compression: "gzip"
      retry_enabled: true
      retry_initial_interval: "1s"
      retry_max_interval: "30s"
      retry_max_elapsed_time: "60s"
      interval: "1s"
      request_time_histogram_boundaries:
        [0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, 10.0]
      request_size_histogram_boundaries:
        [64, 256, 1024, 4096, 16384, 65536, 262144, 1048576]

    tracing:
      enabled: true
      endpoint: "otel-collector:4317" # OTLP gRPC endpoint
      timeout: "10s"
      compression: "gzip"
      retry_enabled: true
      retry_initial_interval: "1s"
      retry_max_interval: "30s"
      retry_max_elapsed_time: "60s"
      batch_timeout: "1s"
      max_queue_size: 2048
      max_export_batch_size: 512
      sampling_ratio: 1.0 # 開発: 1.0, ステージング: 0.1, 本番: 0.01
