// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/y-nosuke/aws-observability-ecommerce/backend-api/internal/product/application/usecase"
	"github.com/y-nosuke/aws-observability-ecommerce/backend-api/internal/product/infrastructure/external/storage"
	"github.com/y-nosuke/aws-observability-ecommerce/backend-api/internal/product/presentation/rest/handler"
	"github.com/y-nosuke/aws-observability-ecommerce/backend-api/internal/shared/infrastructure/aws"
)

// Injectors from wire.go:

// InitializeProductHandler はProductHandlerの依存関係を初期化する
func InitializeProductHandler(s3Wrapper *aws.S3ClientWrapper) *handler.ProductHandler {
	imageStorage := storage.NewS3ImageStorageImpl(s3Wrapper)
	uploadProductImageUseCase := usecase.NewUploadProductImageUseCase(imageStorage, "product-images")
	getProductImageUseCase := usecase.NewGetProductImageUseCase(imageStorage, "product-images")
	productHandler := handler.NewProductHandler(uploadProductImageUseCase, getProductImageUseCase)
	return productHandler
}
