receivers:
  otlp:
    protocols:
      grpc:
        endpoint: "0.0.0.0:4317"
      http:
        endpoint: "0.0.0.0:4318"
exporters:
  debug/stdout:
    verbosity: detailed
    sampling_initial: 100
    sampling_thereafter: 100
  otlphttp/loki:
    endpoint: http://loki:3100/otlp
  otlphttp/mimir:
    endpoint: http://mimir:9009/otlp
  otlp/tempo:
    endpoint: "tempo:4317"
    tls:
      insecure: true

service:
  pipelines:
    logs:
      receivers: [otlp]
      exporters: [otlphttp/loki]
    metrics:
      receivers: [otlp]
      exporters: [debug/stdout, otlphttp/mimir]
    traces:
      receivers: [otlp]
      exporters: [otlp/tempo]
