apiVersion: 1

datasources:
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    isDefault: true
    editable: true
    jsonData:
      timeout: 60s
      maxLines: 1000
      derivedFields:
        - name: "TraceID"
          matcherRegex: 'trace_id":"([^"]+)'
          url: "http://localhost:16686/trace/$${__value.raw}"
          datasourceUid: "tempo" # 将来的にJaeger連携用

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    uid: tempo
    isDefault: false
    editable: true

  - name: Mimir
    type: prometheus
    access: proxy
    url: http://mimir:9009/prometheus
    isDefault: false
    editable: true
    jsonData:
      timeInterval: "15s"
      queryTimeout: "60s"
      httpMethod: "POST"
