# Traefik グローバル設定
api:
  dashboard: true
  insecure: true

# エントリーポイント設定
entryPoints:
  web:
    address: ":80"

# Docker Provider 設定
providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
  file:
    directory: "/etc/traefik/dynamic"
    watch: true

# ログ設定
log:
  level: "INFO"

# アクセスログ設定
accessLog: {}
