# infra/traefik/traefik.yml
# 基本的な設定はDocker ComposeのCommand欄で行っているため、必要に応じて拡張設定を追加

api:
  # ダッシュボードを有効にする（開発環境のみ）
  dashboard: true
  insecure: true # 開発環境のみ

# プロバイダー設定
providers:
  docker:
    exposedByDefault: false # 明示的に有効化したサービスのみ対象

# エントリーポイント設定
entryPoints:
  web:
    address: ":80"
    # 必要に応じてHTTPSリダイレクトを設定
    # http:
    #   redirections:
    #     entryPoint:
    #       to: websecure
    #       scheme: https

  # websecure:
  #   address: ":443"

# ログ設定
log:
  level: "INFO"
