name: Backend Deploy

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch: # 手動トリガー用

jobs:
  deploy-lambda:
    name: Build and Deploy Lambda Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Terraformのセットアップを追加
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Get function names from Terraform
        id: get-functions
        run: |
          cd terraform
          # 出力を変数に安全に格納
          OUTPUT=$(terraform output -raw catalog_lambda_function_name || echo "")
          # 出力が空でないか確認
          if [ -z "$OUTPUT" ]; then
            echo "Error: Terraform output for catalog_lambda_function_name is empty"
            exit 1
          fi
          # 出力にスペースやコロンなどの特殊文字が含まれていないか確認
          CLEANED_OUTPUT=$(echo "$OUTPUT" | tr -dc '[:alnum:]-_')
          # 環境変数に設定
          echo "CATALOG_FUNCTION_NAME=$CLEANED_OUTPUT" >> $GITHUB_ENV
          echo "Function name: $CLEANED_OUTPUT"

      - name: Install dependencies for catalog service
        if: hashFiles('backend/catalog-service/**/*.js') != ''
        run: |
          cd backend/catalog-service
          npm ci

      - name: Deploy catalog service
        if: hashFiles('backend/catalog-service/**/*.js') != '' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          cd backend/catalog-service
          zip -r ../catalog-service.zip .
          cd ..
          aws lambda update-function-code --function-name ${{ env.CATALOG_FUNCTION_NAME }} --zip-file fileb://catalog-service.zip
