name: Backend Deploy

on:
  push:
    branches: [main]
    paths:
      - "backend/**"
  pull_request:
    branches: [main]
    paths:
      - "backend/**"
  workflow_dispatch: # 手動トリガー用

jobs:
  deploy-lambda:
    name: Build and Deploy Lambda Functions
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Terraformのセットアップを追加
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.7.5

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Get function names from Terraform
        id: get-functions
        run: |
          cd terraform
          # terraform outputコマンドの結果をファイルに保存
          terraform output -json > terraform_output.json

          # jqを使って関数名を抽出（jqはGitHub Actionsに標準でインストールされています）
          CATALOG_FUNCTION_NAME=$(jq -r '.catalog_lambda_function_name.value' terraform_output.json)

          echo "Function name extracted: $CATALOG_FUNCTION_NAME"

          # 関数名が有効かチェック
          if [[ ! "$CATALOG_FUNCTION_NAME" =~ ^[a-zA-Z0-9-_]+$ ]]; then
            echo "Invalid function name: $CATALOG_FUNCTION_NAME"
            exit 1
          fi

          # 環境変数にセット
          echo "CATALOG_FUNCTION_NAME=$CATALOG_FUNCTION_NAME" >> $GITHUB_ENV

          # 確認のためにもう一度表示
          echo "Function name set to: $CATALOG_FUNCTION_NAME"

      - name: Install dependencies for catalog service
        if: hashFiles('backend/catalog-service/**/*.js') != ''
        run: |
          cd backend/catalog-service
          npm ci

      - name: Deploy catalog service
        if: hashFiles('backend/catalog-service/**/*.js') != '' && github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: |
          cd backend/catalog-service
          zip -r ../catalog-service.zip .
          cd ..
          aws lambda update-function-code --function-name ${{ env.CATALOG_FUNCTION_NAME }} --zip-file fileb://catalog-service.zip
