name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend-test:
    name: Backend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"

      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: ${{ runner.os }}-go-

      - name: Go to backend directory
        run: cd backend

      - name: Test
        run: |
          cd backend
          go test -v ./...

  frontend-test:
    name: Frontend Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: NPM cache (customer)
        uses: actions/cache@v3
        with:
          path: frontend-customer/node_modules
          key: ${{ runner.os }}-npm-customer-${{ hashFiles('frontend-customer/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-customer-

      - name: NPM cache (admin)
        uses: actions/cache@v3
        with:
          path: frontend-admin/node_modules
          key: ${{ runner.os }}-npm-admin-${{ hashFiles('frontend-admin/package-lock.json') }}
          restore-keys: ${{ runner.os }}-npm-admin-

      - name: Install dependencies (customer)
        run: |
          cd frontend-customer
          npm ci

      - name: Install dependencies (admin)
        run: |
          cd frontend-admin
          npm ci

      - name: Lint (customer)
        run: |
          cd frontend-customer
          npm run lint

      - name: Lint (admin)
        run: |
          cd frontend-admin
          npm run lint
