name: Terraform Validate

on:
  push:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform-validate.yml"
  pull_request:
    branches: [main]
    paths:
      - "infra/terraform/**"
      - ".github/workflows/terraform-validate.yml"

jobs:
  validate:
    name: Validate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Terraform Format
        working-directory: infra/terraform
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: infra/terraform
        run: terraform init -backend=false

      - name: Terraform Validate
        working-directory: infra/terraform
        run: terraform validate
